### ISSUE TITLE
Please include hacktober tag and label.

### ISSUE THREAD

**Issue by debasish212** [ashuprince121/Prepration_Code_Repository#27]
Sir , please include the Hacktober feast tag and label .or we will not be considered as participants. So sir please do it asap. And sir also include contribute.md file 

They say:)
Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest.
Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

**Comment by ashuprince121** [comment]
Added , contributing.md file is already in the repo , Let me know if there are any other issues at ashuprince121@gmail.com. 
Thanks 
Regards.
